baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Things I sometimes delve into'
theme = 'm10c'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.highlight]
    style = 'onedark'